export const PERSON_FETCH_ALL = 'PERSON_FETCH_ALL'
export const PERSON_FETCH_ONE = 'PERSON_FETCH_ONE'
export const PERSON_CREATE = 'PERSON_CREATE'
export const PERSON_UPDATE = 'PERSON_UPDATE'
export const PERSON_DELETE = 'PERSON_DELETE'

export const PARTY_FETCH_ALL = 'PARTY_FETCH_ALL'
export const PARTY_FETCH_ONE = 'PARTY_FETCH_ONE'

export const CONSTITUENCY_FETCH_ALL = 'CONSTITUENCY_FETCH_ALL'
export const CONSTITUENCY_FETCH_ONE = 'CONSTITUENCY_FETCH_ONE'